### ISSUE TITLE
Edge/Line wrapping around the components to which it is connected.

### ISSUE THREAD

**Issue by shujaatak** [Arokip/flutter_diagram_editor#21]
It would be so awesome if an optional feature could be included in the fdl which would allow the line to avoid crossing over those components to which it is connected.
Line right now:
![screenshot-1](https://user-images.githubusercontent.com/14161646/111992484-4f032380-8b37-11eb-8290-80a681d24b5d.png)
Required Feature:
![screenshot-3](https://user-images.githubusercontent.com/14161646/111992511-54606e00-8b37-11eb-80cf-5bd3e4cd5933.png)
OR
![screenshot-4](https://user-images.githubusercontent.com/14161646/111992523-575b5e80-8b37-11eb-85cb-ceea52b18748.png)

**Comment by Arokip** [comment]
It's already implemented. In current demo app it's possible by long clicking on the line.
It is intended to allow library user to use their own gesture to make it work.

**Comment by shujaatak** [comment]
Works perfectly!
