### ISSUE TITLE
Highlight component on mouse hover

### ISSUE THREAD

**Issue by shujaatak** [Arokip/flutter_diagram_editor#25]
An optional feature(one can disable for performance) to highlight component when the user moves or hovers the pointer over it.

**Comment by Arokip** [comment]
This feature will not be a part of this library. Library user can implement it in  `onComponentPointerSignal()` function.

In the future it's possible to add it in the demo app. Please open an issue it its [repository](https://github.com/Arokip/fdl_demo_app).
