### ISSUE TITLE
Allow to connect a component to a link.

### ISSUE THREAD

**Issue by shujaatak** [Arokip/flutter_diagram_editor#26]
For example, if there is a link connecting two components and now a user want to connect an another component with that same link like this(useful for circuit diagrams etc):

![Screenshot from 2021-04-11 14-13-22](https://user-images.githubusercontent.com/14161646/114299291-e5da5480-9ad3-11eb-8119-1c5e9e025c1f.png)

**Comment by Arokip** [comment]
In my opinion, user of the library (who would like to create circuit diagram editor) can create a new type of a Component called for example 'link junction'. The component can be small and black. Three (or more) different links can be connected to it, so it will behave as a link crossroads and there is no need to add this specific option to the library.

I want to remain the library light and simple. It still can be quite powerful if you come up with good usage of it.

**Comment by shujaatak** [comment]
Superb thoughts!

**Comment by shujaatak** [comment]
> In my opinion, user of the library (who would like to create circuit diagram editor) can create a new type of a Component called for example 'link junction'. The component can be small and black. Three (or more) different links can be connected to it, so it will behave as a link crossroads and there is no need to add this specific option to the library.

I agree that there is probably no need to add this specific option to the library but having this in the demo would make demo much more verbose and appealing.

**Comment by shujaatak** [comment]
Oh wonderful! You have already added this feature in the demo!
![new screenshot](https://user-images.githubusercontent.com/14161646/114354472-b8e77980-9b87-11eb-8c9e-f324f995d97d.png)
