### ISSUE TITLE
Any plans to migrate to null safety?

### ISSUE THREAD

**Issue by petcupaula** [Arokip/flutter_diagram_editor#27]
Just discovered this package and found it very useful. Are you planning for a null safety migration for the next release?

**Comment by Arokip** [comment]
There is a plan to do that, otherwise this project will be dead soon. However, I cannot tell when it will happen now.

**Comment by stefandevo** [comment]
Hope you find the time...

**Comment by Arokip** [comment]
The package was released with Null Safety today. **Enjoy!** I spent more than 8 hours last two days to make it done. I hope there will be no bugs due to migrating, if so let me know.
