### ISSUE TITLE
Could you help me with saving progress?

### ISSUE THREAD

**Issue by jcleitonss** [Arokip/flutter_diagram_editor#28]
Hi, I would like to be able to save the diagram state in the cache, so as not to lose work, I also want to enable the use of the interconnected diagram by users, could you help me?

I want to use it in a startup that I'm developing has a few more people supporting me, I can repay you with participation.

**Comment by Arokip** [comment]
Hello,
to save the diagram you need to implement a form of custom serialization, remember also to save all custom data of components/links. I did it once with [now really old version of this project](https://github.com/Arokip/fdl_old/tree/master/lib/diagram_editor/graphml). Or you can think about saving it into a database.
