### ISSUE TITLE
Get result of connected components

### ISSUE THREAD

**Issue by jordandevogelaere** [Arokip/flutter_diagram_editor#29]
Hi,

Is it possible to see (fetch) which components are connected to each other?

I would like to save the connected id's to the database.

Thanks in advance. 

Kind regards,

Jordan

**Comment by Arokip** [comment]
Hello,

it is possible to see.

For instance, you can iterate through IDs of the other components to which the one is connected:

```dart
    canvasReader.model.getComponent(oneComponentId).connections.forEach((connection) {
      connection.otherComponentId; // the ID
    });
```
