### ISSUE TITLE
Add/Update documentation on exporting and importing

### ISSUE THREAD

**Issue by GyroGoober** [Arokip/flutter_diagram_editor#37]
In my opinion, exporting a created diagram to import later is, aside from diagram creation, in my opinion, one of the critical features of this library. However, documentation is very limited/non-existent for this topic. 

All I could find was this response regarding a similar issue:
https://github.com/Arokip/flutter_diagram_editor/issues/28#issuecomment-961201909_

Furthermore, the topic of serializing the diagram data is mentioned in these issues:
https://github.com/Arokip/flutter_diagram_editor/issues/31
https://github.com/Arokip/flutter_diagram_editor/issues/8
However, neither offer documentation on how serialization/saving and restoring are to be implemented. 

A simple code snippet showing basic serialization that should be done would help immensely. Optionally, buttons for importing and exporting could be added to one of the examples

**Comment by Arokip** [comment]
In past I already added serialization. Closing now
