### ISSUE TITLE
Whether to support graphic connection

### ISSUE THREAD

**Issue by Big-billed-shark** [Arokip/flutter_diagram_editor#40]
Our project needs images to connect itself. Is it supported?

**Comment by Arokip** [comment]
@Big-billed-shark not sure what you mean. I imagine something like this in the picture, am I right?
<img width="311" alt="Screenshot 2023-06-12 at 9 51 31" src="https://github.com/Arokip/flutter_diagram_editor/assets/20387953/6de5ad37-3eac-4743-802e-741b410c3d97">

**Comment by Big-billed-shark** [comment]
> @Big-billed-shark not sure what you mean. I imagine something like this in the picture, am I right?
> <img alt="Screenshot 2023-06-12 at 9 51 31" width="311" src="https://user-images.githubusercontent.com/20387953/245069022-6de5ad37-3eac-4743-802e-741b410c3d97.png">

Yes

**Comment by Arokip** [comment]
I am sure it's possible with the current version of the package. It has to be implemented probably like this:
1. create connection from component to the same component
2. add some new points/joints on the new created connection when connection itself (two new points to make a triangle)
