### ISSUE TITLE
Question: How do we give a fixed size for the canvas?

### ISSUE THREAD

**Issue by gowda-nirmal** [Arokip/flutter_diagram_editor#41]
Firstly thanks for the wonderful package. I would want to know if we can set the height and width of the canvas itself. Currently, we can scroll infinitely and I need to restrict this.

**Comment by Arokip** [comment]
Hello, thanks for the feedback.

I haven't tested this feature but there is a function `setPosition` in `CanvasStateWriter`. So you can set the position to your limit if a user scrolls the canvas more.
