### ISSUE TITLE
 The method 'globalToLocal' isn't defined for the type 'RenderObject'.

### ISSUE THREAD

**Issue by gjcarver** [Arokip/flutter_diagram_editor#44]
error: The method 'globalToLocal' isn't defined for the type 'RenderObject'. (undefined_method at ... lib\simple_diagram_editor\policy\canvas_widgets_policy.dart:42)

**Comment by aj-dt** [comment]
I had a similar error in the `_onAcceptWithDetails()` method of `ProcessCanvasWidgetsPolicy`. I fixed it by using this code:
```
   final renderBox = context.findRenderObject();
    if (renderBox is! RenderBox) {
      print("Expected a RenderBox but found [${renderBox.runtimeType}]");
      return;
    }
    final Offset localOffset = renderBox.globalToLocal(details.offset);
```

**Comment by gjcarver** [comment]
That seems to work...
It's amazing how many "errors" show up in these packages: the code evolves a lot more than I would have expected...

**Comment by gjcarver** [comment]
This works:
https://github.com/Arokip/fdl_demo_app/tree/null-safety
